name: "Release"

on:
  push:
    branches: 
      - "RC[0-9]/**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - run: echo ":rocket::rocket::rocket:" > ../release_notes.md 
        if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist --release-notes=../release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
